### PR TITLE
Ability to Create Appointment

### PR DESCRIPTION
**Pull request by ClydeFrog04**
## Description ##

Router endpoint and model for creating new endpoints.

## Type ##

- [ ] This is a bugfix.
- [x] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [ ] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Review by CodyBrewer — APPROVED** [review]
Looks good to me. Tested locally

**Comment by ClydeFrog04** [comment]
[Backend routes for appointments](https://trello.com/c/VYqvRWbL/21-backend-routes-for-appointments)

**Review by milosamec — COMMENTED** [review]
Everything looks good !

**Comment by CodyBrewer** [comment]
[Create Appointments](https://trello.com/c/dB0yKIkI/25-create-appointments)

**Review by milosamec — APPROVED** [review]

**Pull request merged**
