### PR TITLE
GET /appointments endpoint

### PR DESCRIPTION
**Pull request by CodyBrewer**
Description

- [x] getAll appointmentsModel function
- [x] GET /appointments route

Type
- [ ] This is a bugfix.
- [x] This is a new feature.
- [x]  This is part of a feature.
Organization
- [ ]  Have you linked this pull request to a Trello card?
- [ ]  Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing
Review
- [ ]  Is this a work in progress?
- [x] Is this ready to be reviewed?
- [ ]  Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by CodyBrewer** [comment]
[Backend routes for appointments](https://trello.com/c/VYqvRWbL/21-backend-routes-for-appointments)

**Comment by CodyBrewer** [comment]
[GET appointments endpoint](https://trello.com/c/BGlg7cjy/26-get-appointments-endpoint)

**Review by jarrod847 — APPROVED** [review]
Looks good

**Review by ClydeFrog04 — APPROVED** [review]

**Comment by CodyBrewer** [comment]
[Get appointments/:appointmentId endpoint](https://trello.com/c/OOFU51kv/56-get-appointments-appointmentid-endpoint)

**Comment by CodyBrewer** [comment]
[Get appointments/:appointmentId endpoint](https://trello.com/c/OOFU51kv/56-get-appointments-appointmentid-endpoint)

**Pull request merged**
