### PR TITLE
Created Migrations for build the database and Seed for Data

### PR DESCRIPTION
**Pull request by tanveersaleem786**
- Create Migration for the following  tables
  - services 
  - animals
  - animal_services
  - locations
  - service_locations
  - bussiness_profiles
  - bussiness_hours
  - user_ratings
  - customer_pets
  - appointments
  - payments
 

- Create different seed files for inserting data into tables
  - services
  - animals
  - animal_services

- Update Profile migration and seeding by adding following fields
  - user_type
  -  rating

### CODE REVIEW

**Review by TylerAlsop — DISMISSED** [review]
Great job formatting all the files to get rid of the linting errors!
Below I have outlined my review for each file that was changed/created in this pull request. There are only two files that I have suggestions for additions: data/seeds/001_profiles.js and data/seeds/006_states.js.

data/migrations/20201021210955_profile-schema-update.js:
     -Looks good.

data/migrations/20201021211050_create-services.js:
     -Good job.

data/migrations/20201021211130_create-animals.js:
     -This file looks great

data/migrations/20201021211210_create-countries.js:
     -Looks good

data/migrations/20201021211503_create-states.js:
     -Nicely done

data/migrations/20201021211601_create-cities.js:
     -Looks good

data/migrations/20201021211638_create-locations.js: 
     -I like how things like phone number are not nullable

data/migrations/20201021211709_create-business-profiles.js:
     -Good job making sure that the profile_id is a string and not an integer

data/migrations/20201021211751_create-service-locations.js:
     -Good job

data/migrations/20201021211841_create-animal-services.js:
     -Looks good

data/migrations/20201021211915_create-business-hours.js:
     -Well done.

data/migrations/20201021211952_create-user-ratings.js:
     -Looks nice

data/migrations/20201021212020_create-customer-pets.js:
     -Good job adding the pets birthday to be a date.

data/migrations/20201021212054_create-appointments.js:
     -I like all the options

data/migrations/20201021212127_create-payments.js:
     -Very clean. Good job.

data/seeds/000_cleanup.js:
     -Looks like a nice cleanup file

data/seeds/001_profiles.js:
     -Line 5: Is there a way to have some be ‘Customer’ and some be ‘Groomer’? I believe that the front end will filter out all of the Customer profiles in order to search for the Groomer profiles.
     -Would this work?
user_type: (idx % 2) === 0 ? 'Customer' : 'Groomer'

data/seeds/002_services.js:
     -Well done

data/seeds/003_animals.js:
     -Looks good

data/seeds/004_animal_services.js:
     -Good seeding for each of the seed services and seed animals

data/seeds/005_countries.js:
     -Wow! Great seeding of the countries! So many!

data/seeds/006_states.js:
     -Lots of states! Could we find a db that has the states of the United States? I can help look.

**Review by TylerAlsop — COMMENTED** [review]
Great job formatting all the files to get rid of the linting errors!
Below I have outlined my review for each file that was changed/created in this pull request. There are only two files that I have suggestions for additions: data/seeds/001_profiles.js and data/seeds/006_states.js.

data/migrations/20201021210955_profile-schema-update.js:
     -Looks good.

data/migrations/20201021211050_create-services.js:
     -Good job.

data/migrations/20201021211130_create-animals.js:
     -This file looks great

data/migrations/20201021211210_create-countries.js:
     -Looks good

data/migrations/20201021211503_create-states.js:
     -Nicely done

data/migrations/20201021211601_create-cities.js:
     -Looks good

data/migrations/20201021211638_create-locations.js: 
     -I like how things like phone number are not nullable

data/migrations/20201021211709_create-business-profiles.js:
     -Good job making sure that the profile_id is a string and not an integer

data/migrations/20201021211751_create-service-locations.js:
     -Good job

data/migrations/20201021211841_create-animal-services.js:
     -Looks good

data/migrations/20201021211915_create-business-hours.js:
     -Well done.

data/migrations/20201021211952_create-user-ratings.js:
     -Looks nice

data/migrations/20201021212020_create-customer-pets.js:
     -Good job adding the pets birthday to be a date.

data/migrations/20201021212054_create-appointments.js:
     -I like all the options

data/migrations/20201021212127_create-payments.js:
     -Very clean. Good job.

data/seeds/000_cleanup.js:
     -Looks like a nice cleanup file

data/seeds/001_profiles.js:
     -Line 5: Is there a way to have some be ‘Customer’ and some be ‘Groomer’? I believe that the front end will filter out all of the Customer profiles in order to search for the Groomer profiles.
     -Would this work?
user_type: (idx % 2) === 0 ? 'Customer' : 'Groomer'

data/seeds/002_services.js:
     -Well done

data/seeds/003_animals.js:
     -Looks good

data/seeds/004_animal_services.js:
     -Good seeding for each of the seed services and seed animals

data/seeds/005_countries.js:
     -Wow! Great seeding of the countries! So many!

data/seeds/006_states.js:
     -Lots of states! Could we find a db that has the states of the United States? I can help look.

**Comment by MLucky518** [comment]
All of the seeding and migrations look great...really thought out and helpful. This data will be very useful on the front end when we start adding more core features. I agree with Tyler on the countries thing....just wondering if country is necessary if our mapping will use lat/lon

**Review by MLucky518 — COMMENTED** [review]
All of the seeding and migrations look great...really thought out and helpful. This data will be very useful on the front end when we start adding more core features. I agree with Tyler on the countries thing....just wondering if country is necessary if our mapping will use lat/lon

**Comment by tanveersaleem786** [comment]
At this level we are not sure about country table so we will keep it now and see what happen when we will start working on search

**Pull request merged**
