### PR TITLE
Feature/refactor database for groomer profiles

### PR DESCRIPTION
**Pull request by ClydeFrog04**
## Description
Create groomer-cover-images table
Added columns to business profiles table
Create location-services-features table
Type
- [ ] This is a bugfix.
- [x] This is a new feature.
- [x] This is part of a feature.
## Organization
- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing
## Review
- [ ] Is this a work in progress?
- [x]  Is this ready to be reviewed?
- [ ]  Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by ClydeFrog04** [comment]
[Create Groomer_Cover_images Table](https://trello.com/c/M5wJRcew/79-create-groomercoverimages-table)

**Comment by ClydeFrog04** [comment]
[Add Columns to Business Profiles Table](https://trello.com/c/Qb7byRlf/74-add-columns-to-business-profiles-table)

**Comment by ClydeFrog04** [comment]
[Create Location_Services_Features Table](https://trello.com/c/maHu5vGy/78-create-locationservicesfeatures-table)

**Review by CodyBrewer — APPROVED** [review]
Looks good these should help us store and serve up the data needed for groomer profiles in the frontend

**Review by milosamec — APPROVED** [review]
Looks good!

**Pull request merged**
